name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "1 1 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # base: header
          # plugin_languages: yes
          # plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, vue, scala, c, c++, python, ejs
          # plugin_languages_skipped: lowlighter
          # plugin_languages_details: lines, percentage
          # plugin_languages_sections: most-used, recently-used
          # plugin_languages_indepth: yes
          # plugin_languages_limit: 2
          
